# job_store.py placeholder
"""
WHAT: A lightweight, in-memory state manager to track the progress of AI generation jobs.
WHY: Generating AI assets (video, audio, etc.) takes time. The frontend cannot wait synchronously 
     for an HTTP request to finish. Instead, the API returns a job_id immediately (async pattern), 
     and the frontend polls for updates. 
     
     Tradeoff: We use an in-memory Python dictionary here for absolute simplicity and to avoid 
     the overhead of setting up a database (like PostgreSQL or Redis) in this stage of development.
     The major tradeoff is volatility: if the FastAPI server restarts or crashes, all job history 
     is permanently lost. For a production app at scale, this would be replaced with Redis or a DB.
HOW: We use Python's built-in `dict` mapped by UUID strings. A set of helper functions is exposed 
     to safely create and mutate job states throughout the pipeline's execution.
"""

import uuid
from datetime import datetime, timezone
from typing import Dict, Any, Optional

# Pre-defined status constants to prevent typos across the application
STATUS_QUEUED = "QUEUED"
STATUS_EXPANDING_PROMPT = "EXPANDING_PROMPT"
STATUS_GENERATING_IMAGE = "GENERATING_IMAGE"
STATUS_ESTIMATING_DEPTH = "ESTIMATING_DEPTH"
STATUS_GENERATING_AUDIO = "GENERATING_AUDIO"
STATUS_GENERATING_VIDEO = "GENERATING_VIDEO"
STATUS_COMPLETED = "COMPLETED"
STATUS_PARTIAL_FAILURE = "PARTIAL_FAILURE"
STATUS_FAILED = "FAILED"

# The global in-memory dictionary storing all job states
_jobs: Dict[str, Dict[str, Any]] = {}

def create_job() -> str:
    """
    WHAT: Initializes a new job record with a unique ID and a QUEUED status.
    WHY: Called exactly once when the user submits a POST request to generate a scene.
    HOW: Generates a uuid4 string, constructs the initial state dictionary, stores it, and returns the ID.
    """
    job_id = str(uuid.uuid4())
    _jobs[job_id] = {
        "status": STATUS_QUEUED,
        "stage": "Initializing...",
        "assets": {}, # Maps asset_type (e.g., 'image', 'audio') to file URLs
        "error": None,
        "scene_description": None, # Expanded prompt from the Prompt Expander
        "created_at": datetime.now(timezone.utc).isoformat()
    }
    return job_id

def set_job_scene_description(job_id: str, scene_description: str) -> None:
    """
    WHAT: Stores the expanded scene description generated by the prompt expander.
    WHY: Helps users understand what the AI understood from their original prompt.
    """
    job = _jobs.get(job_id)
    if job:
        job["scene_description"] = scene_description

def get_job(job_id: str) -> Optional[Dict[str, Any]]:
    """
    WHAT: Retrieves the current state of a specific job.
    WHY: Used by the GET /status/{job_id} and GET /result/{job_id} endpoints so the frontend 
         can monitor progress or retrieve final URLs.
    HOW: Looks up the job_id in the _jobs dictionary. Returns None if the job doesn't exist.
    """
    return _jobs.get(job_id)

def update_job_status(job_id: str, status: str, stage_description: str = "") -> None:
    """
    WHAT: Updates the status and human-readable stage of an ongoing job.
    WHY: As the pipeline orchestrator moves from Prompt -> Image -> Depth -> Audio -> Video, 
         it needs to communicate where it currently is.
    HOW: Fetches the job from the dict and mutates the "status" and "stage" keys.
    """
    job = _jobs.get(job_id)
    if job:
        job["status"] = status
        # If no custom description is provided, just use the status string as a fallback
        job["stage"] = stage_description or status

def update_job_asset(job_id: str, asset_type: str, file_url: str) -> None:
    """
    WHAT: Attaches a generated asset's URL to the job record.
    WHY: When a pipeline stage finishes (e.g., Image Generation), we need to save the URL 
         to the resulting image so the frontend can download it.
    HOW: Mutates the "assets" dictionary inside the specific job record.
    """
    job = _jobs.get(job_id)
    if job:
        job["assets"][asset_type] = file_url

def set_job_error(job_id: str, error_message: str, partial_failure: bool = False) -> None:
    """
    WHAT: Marks a job as failed and records the error message.
    WHY: AI models can throw Out-of-Memory exceptions or timeout. We must catch these gracefully 
         and inform the user, rather than leaving the job hanging in a "GENERATING" state forever.
    HOW: Sets the status to FAILED (or PARTIAL_FAILURE if some models succeeded but others failed), 
         records the exact error trace, and stores an ISO timestamp of when the error occurred.
         DESIGN CHOICE: Adding an "error_at" timestamp allows the frontend to show human-readable 
         time-ago messages like "failed 2 minutes ago" instead of just showing a static error message.
         We use UTC to avoid timezone issues across different user locations.
    """
    job = _jobs.get(job_id)
    if job:
        job["status"] = STATUS_PARTIAL_FAILURE if partial_failure else STATUS_FAILED
        job["error"] = error_message
        job["error_at"] = datetime.now(timezone.utc).isoformat()
        job["stage"] = "Pipeline execution halted due to error."